name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout norx code
        uses: actions/checkout@v4

      # ✅ 使用 Token 配置 Git 凭据
      - name: Configure Git Credentials
        run: |
          git config --global url."https://${{ secrets.DART_WORKFLOW_TRIGGER }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.DART_WORKFLOW_TRIGGER }}@github.com/".insteadOf "git@github.com:"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web